src/Entity/Property.php
<?php

namespace App\Entity;

use DateTime;
use App\Entity\Option;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PropertyRepository;
use Symfony\Component\HttpFoundation\File;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Entity\File as EntityFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @vich\Uploadable()
 */
class Property 
{
    const HEAT=[
        0 =>'Electrique',
        1 =>'Gaz'
    ];
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10,max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="boolean",options={"default":false})
     */
    private $sold=false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedroom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $room;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;        

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\dateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\dateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getBedroom(): ?int
    {
        return $this->bedroom;
    }

    public function setBedroom(int $bedroom): self
    {
        $this->bedroom = $bedroom;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getRoom(): ?int
    {
        return $this->room;
    }

    public function setRoom(int $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }
   
    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return property
     */
    public function setFilename(?string $filename): Property
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Property
     */
    public function setImageFile($imageFile): Property
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile)
        {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }   
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('price')
            ->add('floor')
            ->add('adress')
            ->add('code_postal')
            ->add('sold')
            ->add('bedroom')
            ->add('city')
            ->add('room')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'required' => false,
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }
    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Form\ContactType;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Notification\ContactNotification;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }
    /**
     * @Route ("/biens", name="Property.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
            $this->repository->findAllvisibleQuery($search),
            $request->query->getInt('page', 1),
            12
        );
        return new Response($this->render('Property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]));
    }
    /**
     * @Route ("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response
    {
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            $this->addFlash('success', 'votre email a bien été envoyé');
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }

        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'form' => $form->createView()
        ]);
    }
}

templates/Property/_property.html.twig
{% cache 'property' ~ property.id property.updatedAt.timestamp %}
<div class="card mb-4">
	{% if property.filename %}
		<img src="{{ vich_uploader_asset(property,'imageFile') | imagine_filter('thumb') }}" alt="card-img-top">
	{% else %}
		<img src="{{ '/images/properties/blog-recent-posts-4.jpg' | imagine_filter('thumb') }}" alt="card-img-top">
	{% endif %}
	<div class="card-body">
		<h5 class="card-title">
			<a href="{{ path('property.show', {slug: property.slug , id: property.id})}}">
				{{ property.title }}
			</a>
		</h5>
		<p class="card-text">{{ property.surface }}m² -
			{{ property.city }}
			({{ property.codePostal }})
		</p>
		<div class="text-primary" style="font: size 2rem; font-weigth: bold;">
			{{ property.price |number_format(0, '', ' ')}}$
		</div>
	</div>
</div>
{% endcache %}

templates/Property/index.html.twig
{% extends "base.html.twig" %}
{% block title 'Tous nos biens' %}


{% block body %}
	<div class="jumbotron">
		<div class="container mt-4">
			{{ form_start(form) }}
			<div class="row ">
				<div class="col">
					{{ form_row(form.minSurface) }}
				</div>
				<div class="col">
					{{ form_row(form.maxPrice) }}
				</div>
				<div class="col">
					{{ form_row(form.options) }}
				</div>
				<div class="col">
					<button class="btn btn-primary">Rechercher</button>
				</div>
			</div>
			{{ form_end(form) }}
		</div>
	</div>
	<div class="container mt-4">
		<h1>Tous nos biens</h1>
		<div class="row">
			{% for property in properties %}
				<div class="col-md-4">
					{% include 'property/_property.html.twig' %}
				</div>
			{% endfor %}
		</div>
		<div class="pagination">
			{{ knp_pagination_render(properties) }}
		</div>
	</div>
{% endblock %}

templates/Property/show.html.twig
{% extends "base.html.twig" %}
{% block title property.title %}

{% block body %}
	<section class="jumbotron">
		<div class="container">
			{% for message in app.flashes('success') %}
				<div class="alert alert-success">
					{{ message }}
				</div>
			{% endfor %}

			{% if not form.vars.valid %}
				<div class="alert-alert-danger">
					Erreur
				</div>
			{% endif %}
			<div class="row">
				<div class="col-md-8">
					{% if property.filename %}
						<img src="{{ vich_uploader_asset(property,'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width:100%; height:auto;">
					{% else %}
						<img src="{{ '/images/properties/blog-recent-posts-4.jpg' | imagine_filter('medium') }}" alt="card-img-top" style="width:100%; height:auto;">
					{% endif %}
				</div>
				<div class="col-md-4">
					<h1>{{ property.title }}</h1>
					<h2>{{ property.room }}
						pièces -
						{{property.surface}}m²</h2>
					<div class="text-primary" style="font: size 4rem; font-weight:bold;">{{ property.price |number_format(0, '', ' ')}}$</div>
					<a href="#" class="btn btn-primary" id="contactButton" {%if form.vars.submitted %} style="display:none;" {% endif %}>Contacter l'agence</a>
					<div id="contactForm" class="mt-4" {%if not form.vars.submitted %} style="display:none;" {% endif %}>
						{{ form_start(form) }}
						<div class="row">
							<div class="col">{{ form_row(form.firstname, {'label':'Nom'})  }}</div>
							<div class="col">{{ form_row(form.lastname,{'label':'Prénom'}) }}</div>
						</div>
						<div class="row">
							<div class="col">{{ form_row(form.email) }}</div>
							<div class="col">{{ form_row(form.phone,{'label':'Téléphone'}) }}</div>
						</div>
						{{ form_rest(form) }}
						<div class="form-group">
							<button class="btn btn-primary">Envoyer</button>
						</div>
						{{ form_end(form) }}
					</div>
				</div>
			</div>
		</div>
	</section>
	<div class="container mt-4">
		<p>
			{{ property.description | nl2br }}
		</p>

		<div class="row">
			<div class="col-md-8">
				<h2>Caractéristiques</h2>
				<table class="table table-striped">
					<tr>
						<td>Surface habitable</td>
						<td>{{ property.surface }}m²</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{ property.room }}</td>
					</tr>
					<tr>
						<td>Chambres</td>
						<td>{{ property.bedroom }}</td>
					</tr>
					<tr>
						<td>Etage</td>
						<td>{{ property.floor }}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>{{ property.heatType }}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-4">
				<h2>Spécificités</h2>
				<ul class="list-group">
					{% for option in property.options %}
						<li class="list-group-item">{{ option.name }}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		<nav class="nav nav-tabs" id="tab"></nav>
	</div>
{% endblock %}